### ISSUE TITLE
how to set content/text of an element

### ISSUE THREAD

**Issue by kaiwu** [clear-code/xmlua#13]
the lib looks excellent in `parse`, how it builds a XML like 

```
<root>
<sub>how to set this part</sub>
</root>
```
`append` and `insert` methods are adding other elements not `content/text`

**Comment by kou** [comment]
[`xmlua.XML.build`[(https://clear-code.github.io/xmlua/reference/xml.html#build) and `xmlua.Element:append` (it's not documented yet) will help you.

**Comment by kaiwu** [comment]
nice,  will check them out

**Comment by kaiwu** [comment]
`xmlua.Element:append_text` works as expected, looking forward it be documented, thanks
