### ISSUE TITLE
Failed to parse XML: internal. Error: Huge input lookup

### ISSUE THREAD

**Issue by felixfire** [clear-code/xmlua#18]
`>>> xmlua.XML.parse(xml_doc)
`

![image](https://user-images.githubusercontent.com/57074430/73180750-fef12280-4126-11ea-8da2-f57a112ca6ca.png)

Version:  1.1.4

**Comment by kou** [comment]
Could you provide a XML that reproduces this case?

**Comment by felixfire** [comment]
You can use this python script for generating a similar XML file.   
As I understand it, this happens when I use Unicode.

```
NODES_COUNT = 100000
CHUNK_SIZE = 1024*1024


data = '''
	<node attr="Attr">
		<title attr="Attr">Title</title>
		<description attr="Attr">%s</description>
	</node>
''' % (''.join(chr(1000+i) for i in range(300))) * NODES_COUNT


doc = '''<?xml version="1.0" encoding="UTF-8"?>
<root>
%s
</root>
''' % data

with open("example.xml", "w") as f:
    for i in range(0, len(doc), CHUNK_SIZE):
        f.write(doc[i:i + CHUNK_SIZE])	

```

**Comment by felixfire** [comment]
My solution: add XML_PARSE_HUGE parse option to xml2.xmlCtxtReadMemory

![image](https://user-images.githubusercontent.com/57074430/73252367-b50e4800-41cb-11ea-9da1-8bfa149089bd.png)

**Comment by kou** [comment]
Thanks.
I've added a feature to pass `XML_PARSE_HUGE`:

```lua
xmlua.XML.parse(xml, {parse_options = {"default", "huge"}})
```
