### ISSUE TITLE
Unable to install xmlua using luarocks. 

### ISSUE THREAD

**Issue by rajibhsingh** [clear-code/xmlua#21]
Hi,
I'm able to get the particular xmlua folder in mysystem from `% sudo apt install -y -V libxml2 && sudo luarocks install xmlua` but now when I'm importing that in my program I'm getting error as

```text
lua: xml.lua:1: module 'xmlua' not found:
        no field package.preload['xmlua']
        no file './xmlua.lua'
        no file '/usr/local/bin/../lib/lua/xmlua.lua'
        no file '/usr/local/bin/../lib/lua/xmlua/init.lua'
        no file './xmlua/init.lua'
        no file './xmlua.so'
        no file '/usr/local/bin/../lib/lua/xmlua.so'
        no file '/usr/local/bin/../lib/lua/loadall.so'
stack traceback:
        [C]: in function 'require'
        xml.lua:1: in main chunk
        [C]: ?
```

I tried moving that folder to other location too like in "/usr/local/lib/lua/5.1" but still getting the same error.

**Comment by komainu8** [comment]
Thank you for your report.

Could you provide the result of the below command?

```shell
% luarocks path
```

XMLua is installed `/usr/local/share/lua/5.1/` by default.
Probably,  LUA_PATH doesn't include the above path.

Do you installed luarocks from source code?

**Comment by rajibhsingh** [comment]
Hey, Thank you for your reply
here is the path of luarocks :- 
"export LUA_PATH='/home/rajib/.luarocks/share/lua/5.1/?.lua;/home/rohan/.luarocks/share/lua/5.1/?/init.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua;./?.lua;/usr/local/lib/lua/5.1/?.lua;/usr/local/lib/lua/5.1/?/init.lua;/usr/share/lua/5.1/?.lua;/usr/share/lua/5.1/?/init.lua'
export LUA_CPATH='/home/rajib/.luarocks/lib/lua/5.1/?.so;/usr/local/lib/lua/5.1/?.so;./?.so;/usr/lib/x86_64-linux-gnu/lua/5.1/?.so;/usr/lib/lua/5.1/?.so;/usr/local/lib/lua/5.1/loadall.so'
"
and Yes you are right xmlua is default not getting installed at /usr/local/share/lua/5.1/ it is getting in "/usr/local/lib/luarocks/rocks/xmlua "
can you help me with this how to fix the issue.

**Comment by komainu8** [comment]
Thank you for your information.

I think There is not `xmlua.lua` into `/usr/local/lib/luarocks/rocks/xmlua` probably.
Because `/usr/local/lib/luarocks/rocks/xmlua` is directory to store manifest(ex. xmlua-1.1.5-0.rockspec) and docs, and etc..

Could you provide the result of the below command?

```
sudo find /* -name "xmlua.lua"
```

If there is `xmlua.lua` in the below like path, could you try to execute `sudo luarocks install xmlua` in a location other than the `luarocks-x.x.x` directory. 

```
/home/xxxxx/luarocks-x.x.x/lua_modules/share/lua/5.1/xmlua.lua
```

**Comment by rajibhsingh** [comment]
Yes you are right there is not xmlua.lua into /usr/local/lib/luarocks/rocks/xmlua.
I tried this "sudo find /* -name "xmlua.lua" and got path as
/home/xxxxx/luarocks-3.3.1/lua_modules/share/lua/5.1/xmlua.lua
then i installed "sudo luarocks install xmlua" in home directory.

Then I tried running Lua in this "/home/xxxxx/luarocks-3.3.1/lua_modules/share/lua/5.1" 
doing all this now "module 'xmlua' not found:" is resolved I guess. But getting another error as
"module 'ffi' not found"

**Comment by komainu8** [comment]
Thank you for your additional information.

If you execute "sudo luarocks install xmlua" in your home directory, xmlua.lua is installed in "/usr/local/share/lua/5.1/".

By this, Lua can found xmlua module from any place.
Because "/usr/local/share/lua/5.1/" includes in LUA_PATH.

The cause of "module 'ffi' not found" is the luajit isn't installed in your system.
Could you try to install luajit by the below command?

```
% sudo apt install luajit
```

**Comment by rajibhsingh** [comment]
Thank you Yasuhiro for help,

Now I can see /usr/local/share/lua/5.3/xmlua xmlua at this location.
But even I have installed LuaJIT still getting same error  

 module 'ffi' not found:
	no field package.preload['ffi']
	no file '/usr/local/share/lua/5.3/ffi.lua'
	no file '/usr/local/share/lua/5.3/ffi/init.lua'
	no file '/usr/local/lib/lua/5.3/ffi.lua'
	no file '/usr/local/lib/lua/5.3/ffi/init.lua'
	no file './ffi.lua'
	no file './ffi/init.lua'
	no file '/usr/local/lib/lua/5.3/ffi.so'
	no file '/usr/local/lib/lua/5.3/loadall.so'
	no file './ffi.so'
stack traceback:
	[C]: in function 'require'
	/usr/local/share/lua/5.3/xmlua/libxml2/memory.lua:1: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.3/xmlua/libxml2.lua:3: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.3/xmlua.lua:5: in main chunk
	[C]: in function 'require'
	stdin:1: in main chunk
	[C]: in ?
I have Installed luajit from official website and build using "make && sudo make install"

**Comment by komainu8** [comment]
LuaJIT is  FFI(Foreign function interface) module that compatible Lua5.1.
So, LuaJIT can't use it in the environment of Lua 5.3.

I suggest that use Lua 5.1 and LuaJIT.
Probably, if we install by below steps, we can use XMLua. 

1. Install Lua 5.1
2. Install LuaRocks
3. Install Luajit
4. Install XMLua by luarocks command

Thanks,

**Comment by kou** [comment]
Do we need to install Lua 5.1?

**Comment by komainu8** [comment]
LuaRocks depend on Lua.
Therefore, If LuaRocks install from source codes, it needs to install Lua.

**Comment by kou** [comment]
I see.

**Comment by kou** [comment]
No more response.
