### ISSUE TITLE
Q: how to include namespaces on serialized child element

### ISSUE THREAD

**Issue by Tieske** [clear-code/xmlua#36]
For example:
```xml
<root xmlns:ns1="http://example.com/ns1" xmlns:ns2="http://example.com/ns2">
  <ns1:child attr="value">
    <ns2:subchild>Content</ns2:subchild>
  </ns1:child>
</root>
```
If I parse this xml and then call `to_xml` on either the `child` or `subchild` elements, I get an xml that doesn't include the namespace definitions, since they were defined on the `root` element.

How can I serialize those elements including the namespace definitions?

**Comment by kou** [comment]
Could you also provide a Lua script you used?

**Comment by kou** [comment]
Thanks.

In libxml2, I couldn't find a convenience API for this use case. So we need to this in XMLua level or user side.

I tried this but it doesn't change the output:

```lua
local xmlua     = require("xmlua")

local basedoc = [[<root xmlns:ns1="http://example.com/ns1" xmlns:ns2="http://example.com/ns2">
  <ns1:child attr="value">
    <ns2:subchild>Content</ns2:subchild>
  </ns1:child>
</root>]]
print("\n======= Original doc =======\n" .. basedoc)

local xmldoc = xmlua.XML.parse(basedoc)
print("\n======= re-serialized doc =======\n" .. xmldoc:to_xml())

local elem = xmldoc:search("//ns1:child")[1]
for _, namespace in ipairs(elem:namespaces()) do
   elem:set_attribute("xmlns:" .. namespace:prefix(), namespace:href())
end
print("\n======= extracted element =======\n" .. elem:to_xml())

-- test to ensure we're not hitting the debug "to_xml" version
local serializable = require "xmlua.serializable"
print("\n======= extracted element using serializable =======\n" .. serializable.to_xml(elem))
```

It seems that we need to remove namespace declarations in `<root>` too...

**Comment by Tieske** [comment]
so the use case is to do canonicalization, that's what I need the namespaces for in the output. Hence also pr #37 to add those functions.
