### ISSUE TITLE
[bug]: notation.lua is missing from the rockspec

### ISSUE THREAD

**Issue by Tieske** [clear-code/xmlua#38]
The file is in the repo, but not in the rockspec, so won't get installed.

**Comment by Tieske** [comment]
fix is in #37

**Comment by kou** [comment]
Could you open a separated PR instead of adding unrelated changes to one PR?

**Comment by Tieske** [comment]
#39 is now a separate PR for this. It is related however, since #37 fails hard without this fix.

**Comment by kou** [comment]
I've merged #39. Could you rebase #37 on master?

**Comment by Tieske** [comment]
done
